baseurl = "https://bmfazio.github.io/"
languageCode = "en-us"
title = "Boris Fazio"
theme = "hugo-xmin"
publishDir = "../bmfazio.github.io/"

googleAnalytics = "UA-141885901-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4

[params]
    description = "Personal website for Boris Fazio"
    footer = "Boris Fazio | [Github](https://github.com/bmfazio) | [Twitter](https://twitter.com/bmfazio)"
